// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: proto/hello-test.proto

package hello_test

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// HelloService defines service.
type HelloService interface {
	Hello(ctx context.Context, req *HelloReq) (*HelloRsp, error)

	Test(ctx context.Context, req *TestReq) (*TestRsp, error)
}

func HelloService_Hello_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &HelloReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(HelloService).Hello(ctx, reqbody.(*HelloReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func HelloService_Test_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &TestReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(HelloService).Test(ctx, reqbody.(*TestReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// HelloServer_ServiceDesc descriptor for server.RegisterService.
var HelloServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.proto.test.Hello",
	HandlerType: ((*HelloService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.proto.test.Hello/Hello",
			Func: HelloService_Hello_Handler,
		},
		{
			Name: "/trpc.proto.test.Hello/Test",
			Func: HelloService_Test_Handler,
		},
	},
}

// RegisterHelloService registers service.
func RegisterHelloService(s server.Service, svr HelloService) {
	if err := s.Register(&HelloServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Hello register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedHello struct{}

func (s *UnimplementedHello) Hello(ctx context.Context, req *HelloReq) (*HelloRsp, error) {
	return nil, errors.New("rpc Hello of service Hello is not implemented")
}
func (s *UnimplementedHello) Test(ctx context.Context, req *TestReq) (*TestRsp, error) {
	return nil, errors.New("rpc Test of service Hello is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// HelloClientProxy defines service client proxy
type HelloClientProxy interface {
	Hello(ctx context.Context, req *HelloReq, opts ...client.Option) (rsp *HelloRsp, err error)

	Test(ctx context.Context, req *TestReq, opts ...client.Option) (rsp *TestRsp, err error)
}

type HelloClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewHelloClientProxy = func(opts ...client.Option) HelloClientProxy {
	return &HelloClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *HelloClientProxyImpl) Hello(ctx context.Context, req *HelloReq, opts ...client.Option) (*HelloRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.proto.test.Hello/Hello")
	msg.WithCalleeServiceName(HelloServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("proto")
	msg.WithCalleeServer("test")
	msg.WithCalleeService("Hello")
	msg.WithCalleeMethod("Hello")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &HelloRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *HelloClientProxyImpl) Test(ctx context.Context, req *TestReq, opts ...client.Option) (*TestRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.proto.test.Hello/Test")
	msg.WithCalleeServiceName(HelloServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("proto")
	msg.WithCalleeServer("test")
	msg.WithCalleeService("Hello")
	msg.WithCalleeMethod("Test")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &TestRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
