// Code generated by MockGen. DO NOT EDIT.
// Source: hello-test.trpc.go
//
// Generated by this command:
//
//	mockgen -destination=hello_test_mock.go -package=hello_test --source=hello-test.trpc.go
//

// Package hello_test is a generated GoMock package.
package hello_test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "trpc.group/trpc-go/trpc-go/client"
)

// MockHelloService is a mock of HelloService interface.
type MockHelloService struct {
	ctrl     *gomock.Controller
	recorder *MockHelloServiceMockRecorder
}

// MockHelloServiceMockRecorder is the mock recorder for MockHelloService.
type MockHelloServiceMockRecorder struct {
	mock *MockHelloService
}

// NewMockHelloService creates a new mock instance.
func NewMockHelloService(ctrl *gomock.Controller) *MockHelloService {
	mock := &MockHelloService{ctrl: ctrl}
	mock.recorder = &MockHelloServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelloService) EXPECT() *MockHelloServiceMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockHelloService) ISGOMOCK() struct{} {
	return struct{}{}
}

// Hello mocks base method.
func (m *MockHelloService) Hello(ctx context.Context, req *HelloReq) (*HelloRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hello", ctx, req)
	ret0, _ := ret[0].(*HelloRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hello indicates an expected call of Hello.
func (mr *MockHelloServiceMockRecorder) Hello(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hello", reflect.TypeOf((*MockHelloService)(nil).Hello), ctx, req)
}

// Test mocks base method.
func (m *MockHelloService) Test(ctx context.Context, req *TestReq) (*TestRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Test", ctx, req)
	ret0, _ := ret[0].(*TestRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Test indicates an expected call of Test.
func (mr *MockHelloServiceMockRecorder) Test(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Test", reflect.TypeOf((*MockHelloService)(nil).Test), ctx, req)
}

// MockHelloClientProxy is a mock of HelloClientProxy interface.
type MockHelloClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockHelloClientProxyMockRecorder
}

// MockHelloClientProxyMockRecorder is the mock recorder for MockHelloClientProxy.
type MockHelloClientProxyMockRecorder struct {
	mock *MockHelloClientProxy
}

// NewMockHelloClientProxy creates a new mock instance.
func NewMockHelloClientProxy(ctrl *gomock.Controller) *MockHelloClientProxy {
	mock := &MockHelloClientProxy{ctrl: ctrl}
	mock.recorder = &MockHelloClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelloClientProxy) EXPECT() *MockHelloClientProxyMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockHelloClientProxy) ISGOMOCK() struct{} {
	return struct{}{}
}

// Hello mocks base method.
func (m *MockHelloClientProxy) Hello(ctx context.Context, req *HelloReq, opts ...client.Option) (*HelloRsp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Hello", varargs...)
	ret0, _ := ret[0].(*HelloRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hello indicates an expected call of Hello.
func (mr *MockHelloClientProxyMockRecorder) Hello(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hello", reflect.TypeOf((*MockHelloClientProxy)(nil).Hello), varargs...)
}

// Test mocks base method.
func (m *MockHelloClientProxy) Test(ctx context.Context, req *TestReq, opts ...client.Option) (*TestRsp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Test", varargs...)
	ret0, _ := ret[0].(*TestRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Test indicates an expected call of Test.
func (mr *MockHelloClientProxyMockRecorder) Test(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Test", reflect.TypeOf((*MockHelloClientProxy)(nil).Test), varargs...)
}
